### ISSUE TITLE
About map parameters

### ISSUE THREAD

**Issue by daleigehhh** [lukovicaleksa/grid-mapping-in-ROS#2]
@lukovicaleksa Hi, great work.
I am a little bit confused about the map parameters x_lim and y_lim, are these values the scale of the whole map or the perceptual field. I think they are the scale of the whole map because you use them in bresenham algorithm, and the environment is simple so you do not need to consider the max range of the laser. Am I right?

I saw a work about crowd navigation in CoRL 2023, which code [code](https://github.com/TempleRAIL/SOGMP)  very similar to this repo.

**Comment by lukovicaleksa** [comment]
Hi Leizi,

Thanks, Im glad you find it useful.

I had a look at the code since I did this long ago and yes, you are right,
limits are for the whole map.

Best regards,
Aleksa
